apiVersion: 1

datasources:
  - name: ClickHouse
    uid: P_NOAA_CLICKHOUSE
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: noaa
      username: noaa
    secureJsonData:
      password: noaa_local
    editable: true
